sudo: required

# Enable C++ support
language: cpp

os:
  - linux
  - osx

# Compiler selection
compiler:
  - clang++

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install clang; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ruby --version; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rvm install ruby-2.3.3; rvm --default use 2.3.3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ruby --version; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ruby --version; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ninja; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install rust; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -L "https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip" -o ninja-linux.zip; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo unzip ninja-linux.zip -d /usr/local/bin; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo chmod 755 /usr/local/bin/ninja; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -sSf https://static.rust-lang.org/rustup.sh | sudo sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pyenv shell 3.5; fi
  - pip3 install meson
  

  
# Build steps
script:
  - meson src build
  - cd build
  - ninja test
  - rm test.text
  - sudo ninja install
  - cd ../fetishes/obedience
  - fetlang unit.fet -o unit_test
  - ./unit_test
  - rm test.text
  - fetlang -O unit.fet -o unit_test_optimized
  - ./unit_test_optimized
  - rm test.text
  - bash ../../scripts/checkdiff.sh unit_test unit_test_optimized
  - cd -

